// @ts-check
/**
 * svg-to-neon — build-time codegen
 * --------------------------------
 * Reads a "plain paths" SVG and emits a typed TS module that <NeonSVG> consumes:
 *
 *     export const splashArt = {
 *       viewBox: { width, height },
 *       paths: string[],   // SVG path "d" strings, in viewBox coordinates
 *     };
 *
 * Why a build step (vs. parsing the SVG at runtime)?
 *  - Metro doesn't hand you raw .svg text by default — it treats .svg as an
 *    asset/component. Bundling the extracted paths as plain JS sidesteps all of
 *    that, costs nothing at runtime, and needs no XML parser on-device.
 *  - To update the art: edit the SVG, then re-run this (the `prestart` npm hook
 *    runs it automatically before `expo start`).
 *
 * Scope: handles <path d="…"> and <line x1 y1 x2 y2>. Both are present in
 * splash.svg. Other primitives (rect/circle/polygon) would need adding here.
 *
 * Usage:  node scripts/svg-to-neon.mjs [input.svg] [output.ts] [exportName]
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");

const input = resolve(repoRoot, process.argv[2] ?? "assets/images/splash.svg");
const output = resolve(
    repoRoot,
    process.argv[3] ?? "src/generated/splash-paths.ts",
);
const exportName = process.argv[4] ?? "splashArt";

/** Pull the numeric value of an attribute out of an SVG tag string. */
function attr(tag, name) {
    const m = tag.match(new RegExp(`${name}\\s*=\\s*"([^"]*)"`, "i"));
    return m ? m[1] : null;
}

function num(tag, name) {
    const v = attr(tag, name);
    return v == null ? 0 : parseFloat(v);
}

function main() {
    const svg = readFileSync(input, "utf8");

    // ── viewBox → { width, height } ────────────────────────────────────────────
    const vbMatch = svg.match(/viewBox\s*=\s*"([^"]+)"/i);
    if (!vbMatch) throw new Error(`No viewBox found in ${input}`);
    const [, , vbW, vbH] = vbMatch[1]
        .trim()
        .split(/[\s,]+/)
        .map(Number);
    if (!vbW || !vbH)
        throw new Error(`Bad viewBox "${vbMatch[1]}" in ${input}`);

    const paths = [];

    // ── <path d="…"> — order preserved = draw order ────────────────────────────
    for (const tag of svg.match(/<path\b[^>]*>/gi) ?? []) {
        const d = attr(tag, "d");
        if (d && d.trim()) paths.push(d.trim().replace(/\s+/g, " "));
    }

    // ── <line> → "M x1 y1 L x2 y2" ─────────────────────────────────────────────
    for (const tag of svg.match(/<line\b[^>]*>/gi) ?? []) {
        const x1 = num(tag, "x1");
        const y1 = num(tag, "y1");
        const x2 = num(tag, "x2");
        const y2 = num(tag, "y2");
        paths.push(`M ${x1} ${y1} L ${x2} ${y2}`);
    }

    if (paths.length === 0) {
        throw new Error(`No <path>/<line> elements found in ${input}`);
    }

    // ── Emit ───────────────────────────────────────────────────────────────────
    const banner =
        `// AUTO-GENERATED by scripts/svg-to-neon.mjs — DO NOT EDIT BY HAND.\n` +
        `// Source: ${process.argv[2] ?? "assets/images/splash.svg"}\n` +
        `// Regenerate: npm run gen:svg  (also runs automatically on \`npm start\`).\n\n`;

    const body =
        `export const ${exportName} = {\n` +
        `  viewBox: { width: ${vbW}, height: ${vbH} },\n` +
        `  paths: [\n` +
        paths.map((d) => `    ${JSON.stringify(d)},`).join("\n") +
        `\n  ],\n} as const;\n`;

    mkdirSync(dirname(output), { recursive: true });
    writeFileSync(output, banner + body, "utf8");

    console.log(
        `svg-to-neon: ${paths.length} path(s) → ${output.replace(repoRoot + "/", "")}` +
            ` (viewBox ${vbW}×${vbH})`,
    );
}

main();
